# Generated by Django 4.2 on 2023-04-28 00:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ordem", "0002_rename_usuario_ordem_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ordem",
            old_name="user",
            new_name="user_id",
        ),
    ]
