# Generated by Django 4.2 on 2023-04-28 04:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("produto", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="produto",
            name="ativo",
        ),
    ]
