# Generated by Django 4.2 on 2023-04-28 00:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ordem", "0004_rename_user_id_ordem_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ordem",
            old_name="user",
            new_name="a",
        ),
    ]
